services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.4"
      PACKWIZ_URL: "https://raw.githubusercontent.com/auggeythecat/SummerFabricV2/refs/heads/main/packwiz%20modpack%20(1.20.4)/pack.toml"
      JVM_OPTS: "-Xmx8g"
    volumes:
      - "./data (1.20.4):/data"