name = "1.20.4"
author = "auggiethecat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a03a3298a406e010abf963d4edf0dac9e384c510340e6e7ddb0a625c5e0d3cc6"

[versions]
fabric = "0.16.10"
minecraft = "1.20.4"
