name = "1.20.4"
author = "auggiethecat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3e42d07be11a053e324de168805dd65f7722bc7b30fa9455d36579e087229af"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
