name = "1.20.4"
author = "auggiethecat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "849526d30a11d20f7c92970c28971cfb9e713f6671499f6eb69de3aa8f82f3fc"

[versions]
fabric = "0.16.10"
minecraft = "1.20.4"
