name = "1.20.4"
author = "auggiethecat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "648f576c9479bd0ebd0648e6d725bd436ec518c17afc1d1aa92c57811001f554"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
